# This file is placed at the root of your repository.
# It tells Netlify how to build and deploy your site.

[build]
  # The command to build your Next.js site.
  # Netlify will run this command from the 'base' directory.
  command = "pnpm run build"
  publish = ".next"
  base = "frontend"

[[plugins]]
  # This is the essential plugin for deploying Next.js sites on Netlify.
  # It ensures that features like SSR, ISR, and Image Optimization work correctly.
  package = "@netlify/plugin-nextjs"